# Generated by Django 5.1 on 2024-10-11 07:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Website", "0007_alter_orderplaced_payment_alter_orderplaced_status_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together=set(),
        ),
    ]
